version: '3.8'

services:
  app:
    build: .
    container_name: app_crud
    ports:
      - "8080:80"
    volumes:  
      - ./:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: crud_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crud
      MYSQL_USER: henrique
      MYSQL_PASSWORD: Sx12356$
    ports:
      - "3306:3306"
